### ISSUE TITLE
Style block not getting added

### ISSUE THREAD

**Issue by volfyd** [CyberShadow/DuolingoMoreKeys#2]
Hi,

Just today duolingo seems to have updated something that breaks styling. I don't know why but the style block isn't getting added. If I move the call of addGlobalStyle from DOMContentLoaded to after the "        // New exercise" line it works (but presumably continues to add the style over and over).

**Comment by CyberShadow** [comment]
I don't see this problem on my end. #3 does occur though.

**Comment by volfyd** [comment]
I guess it could be an A/B test.

**Comment by CyberShadow** [comment]
What about using the "load" event instead of "DOMContentLoaded"?

**Comment by volfyd** [comment]
I reverted my changes to the script and it's working without them now (using DOMContentLoaded). *shrug*

**Comment by CyberShadow** [comment]
OK, let me know if you run into this again.
