### ISSUE TITLE
Compatibility with preview.duolingo.com

### ISSUE THREAD

**Issue by Atervanda** [CyberShadow/DuolingoMoreKeys#5]
Hi,

Thank you for this wonderful script! If it's not too much trouble, could you make it compatible with https://preview.duolingo.com, the site for beta testers?

Thanks in advance!

**Comment by CyberShadow** [comment]
I added the URL. Hopefully the actual implementation won't break too often.

**Comment by Atervanda** [comment]
Many thanks!
